name: CI
permissions: {}

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Install linters
        run: sudo apt-get install -y pyflakes3 pycodestyle pydocstyle codespell pylint

      - name: Run tests
        run: make test
